# Generated by Django 3.1.7 on 2021-10-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
