# Generated by Django 3.1.7 on 2021-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_tasksubmission_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
